#!/bin/bash

# Setup GitHub labels for the Matterbridge AI Plugin Factory
# Requires: gh CLI authenticated

set -e

REPO="${1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"

echo "Setting up labels for repository: $REPO"

# Function to create or update a label
create_label() {
    local name="$1"
    local color="$2"
    local description="$3"
    
    echo "Creating/updating label: $name"
    
    # Try to create, if exists, update
    gh label create "$name" --color "$color" --description "$description" --repo "$REPO" 2>/dev/null || \
    gh label edit "$name" --color "$color" --description "$description" --repo "$REPO" 2>/dev/null || \
    echo "  Warning: Could not create/update label $name"
}

# Request Status Labels
create_label "plugin-request" "0052CC" "A request for a new Matterbridge plugin"
create_label "pending-review" "FBCA04" "Waiting for AI agent to process"
create_label "in-progress" "5319E7" "AI agent is working on this plugin"
create_label "ready-for-testing" "0E8A16" "Plugin is ready for user testing"
create_label "needs-revision" "D93F0B" "Plugin needs fixes based on feedback"
create_label "needs-info" "E99695" "More information needed from requester"
create_label "completed" "2EA44F" "Plugin successfully created and tested"
create_label "error" "B60205" "An error occurred during processing"

# Category Labels
create_label "ai-factory" "1D76DB" "Processed by AI Plugin Factory"
create_label "ai-generated" "7057FF" "Code generated by AI"

# Device Type Labels
create_label "device-light" "FEF2C0" "Light/Bulb device"
create_label "device-switch" "D4C5F9" "Switch/Outlet device"
create_label "device-sensor" "C5DEF5" "Sensor device"
create_label "device-thermostat" "F9D0C4" "Thermostat/Climate device"
create_label "device-lock" "BFDADC" "Lock device"
create_label "device-cover" "D4C5F9" "Cover/Blinds device"

echo ""
echo "✅ Labels setup complete!"
